#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/tcsh

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_53e243.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_53e243.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_5a236c.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_5a236c.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_5bd9c6.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_5bd9c6.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_5d2d89.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_5d2d89.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_6c9934.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_6c9934.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_73f253.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_73f253.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_7c8758.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_7c8758.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_840333.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_840333.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_8d59d9.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_8d59d9.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_a1dff8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_a1dff8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_a59ccc.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_a59ccc.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_a797d2.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_a797d2.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_b57ba1.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_b57ba1.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_cdede6.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_cdede6.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_dc659b.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_dc659b.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_dd39ab.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_dd39ab.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_e00471.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_e00471.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_e2efb4.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_e2efb4.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_fb8b88.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_fb8b88.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_fbcf81.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V002/Wp3j_7TeV_V002_Et25.GeV_fbcf81.root
 


_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
