#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/tcsh

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_30b945.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_30b945.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_332121.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_332121.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_3c8941.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_3c8941.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_444319.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_444319.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_452478.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_452478.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_b6b9db.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm1j/7TeV/R001/Wm1j_7TeV_R001_Et25.GeV_b6b9db.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_43d145.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_43d145.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_4a8204.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_4a8204.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_63b28d.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_63b28d.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_65471e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_65471e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_67bba8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_67bba8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_6a4067.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_6a4067.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_6fba78.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_6fba78.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_7f94ed.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_7f94ed.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_8290ac.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_8290ac.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_8b967b.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_8b967b.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_cd7771.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_cd7771.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_ed42a8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_ed42a8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_f1a022.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_f1a022.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_f59a87.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/I001/Wm2j_7TeV_I001_Et25.GeV_f59a87.root
 


_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
