#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/tcsh

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_c8ddb0.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_c8ddb0.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_cb6cdd.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_cb6cdd.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_cd7624.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_cd7624.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_cd7771.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_cd7771.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_d7f1e2.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_d7f1e2.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_d9f52d.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_d9f52d.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_da820e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_da820e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_db6398.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_db6398.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_dbbc33.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_dbbc33.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_dc47c9.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_dc47c9.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_dd4b8d.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_dd4b8d.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_ddf231.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_ddf231.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_e422ae.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_e422ae.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_e5cbdd.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_e5cbdd.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_e7c0b4.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_e7c0b4.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_ea8d5e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_ea8d5e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f59a87.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f59a87.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f7dd90.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f7dd90.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f7e80e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f7e80e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f82772.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/I001/Wm4j_7TeV_I001_Et25.GeV_f82772.root
 


_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
