#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/tcsh

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_02d943.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_02d943.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_196b35.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_196b35.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_1c0bb0.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_1c0bb0.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_2981af.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_2981af.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_378878.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_378878.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_43d145.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_43d145.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_4a8204.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_4a8204.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_63b28d.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_63b28d.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_65471e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_65471e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_67bba8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_67bba8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_6a4067.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_6a4067.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_6fba78.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_6fba78.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_7f94ed.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_7f94ed.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_8290ac.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_8290ac.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_8b967b.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_8b967b.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_972aa8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_972aa8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_a06eb7.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_a06eb7.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_a25b1b.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_a25b1b.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_ab10b4.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_ab10b4.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_b64a72.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/I001/Wm3j_7TeV_I001_Et25.GeV_b64a72.root
 


_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
