#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/tcsh

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_3fa28e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_3fa28e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_402c3b.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_402c3b.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_408137.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_408137.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_42ae2c.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_42ae2c.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_42d3da.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_42d3da.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4321f5.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4321f5.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_435cd4.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_435cd4.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_442776.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_442776.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_444319.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_444319.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4464f0.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4464f0.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_452478.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_452478.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_454bdc.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_454bdc.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_471045.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_471045.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_481518.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_481518.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_48e166.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_48e166.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_495198.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_495198.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4a18dc.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4a18dc.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4ab163.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_4ab163.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_5040f7.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_5040f7.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_509008.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm4j/7TeV/R001/Wm4j_7TeV_R001_Et25.GeV_509008.root
 


_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
