#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/tcsh

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_ddfc1c.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_ddfc1c.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_ded3c0.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_ded3c0.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_e2359e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_e2359e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_e6acce.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_e6acce.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_eb4ffd.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_eb4ffd.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f449d8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f449d8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f6314d.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f6314d.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f6fac7.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f6fac7.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f7730c.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_f7730c.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fbb82c.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fbb82c.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fbbc3d.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fbbc3d.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fbedc7.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fbedc7.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fc03c8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/R001/Wp3j_7TeV_R001_Et25.GeV_fc03c8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_00eb55.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_00eb55.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_018817.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_018817.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_01c2c9.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_01c2c9.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_01e21c.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_01e21c.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_04f47f.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_04f47f.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_063a91.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_063a91.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_072265.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wp3j/7TeV/V001/Wp3j_7TeV_V001_Et25.GeV_072265.root
 


_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
