#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/tcsh

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_e2359e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_e2359e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_eb4ffd.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_eb4ffd.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_f449d8.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_f449d8.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_f6fac7.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_f6fac7.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_f7730c.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/R001/Wm2j_7TeV_R001_Et25.GeV_f7730c.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_04f47f.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_04f47f.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_0d19de.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_0d19de.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_2365f9.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_2365f9.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_77a3c9.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_77a3c9.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_9d11c5.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm2j/7TeV/V001/Wm2j_7TeV_V001_Et25.GeV_9d11c5.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_07bbc9.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_07bbc9.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_0c4f75.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_0c4f75.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_2ec924.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_2ec924.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_347034.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_347034.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_350697.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_350697.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_536c03.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_536c03.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_5c250e.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_5c250e.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_5e2b19.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_5e2b19.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_647ec5.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_647ec5.root
 

xrdcp "root://castorcms//castor/cern.ch/user/d/dmaitre/BHSNtuples/Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_653134.root" root://eoscms//eos/cms/store/group/phys_smp/WPlusJets/BHSNtuplesV2//Wm3j/7TeV/B001/Wm3j_7TeV_B001_Et25.GeV_653134.root
 


_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
